/**
 * 实验目录 — 按物理课标体系完整覆盖
 *
 * 初中：力学·电学·热学·光学·声学（五大板块）
 * 高中：力学·电磁学·热学·光学·近代物理
 *
 * 难度：★基础  ★★提高  ★★★挑战
 * 标记：★★★必考核心  ★★高频  ★了解
 * 超纲：beyondCurriculum=true 表示超出中学物理课标要求，仅供拓展/竞赛参考
 */

export const EXPERIMENT_CATALOG = [
  // ==================== 初中·力学（8个）====================
  {
    key: 'measureSpeed',
    name: '测量平均速度',
    description: '用刻度尺和秒表测量物体沿斜面运动的平均速度',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 1,
    grade: '八年级',
    tags: ['刻度尺', '秒表', 'v=s/t'],
    examLevel: '★★',
  },
  {
    key: 'densityMeasurement',
    name: '测量物质密度',
    description: '用天平和量筒测量固体和液体的密度',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 2,
    grade: '八年级',
    tags: ['天平', '量筒', 'ρ=m/V', '误差分析'],
    examLevel: '★★★',
  },
  {
    key: 'frictionForce',
    name: '探究滑动摩擦力影响因素',
    description: '控制变量法探究压力和接触面粗糙程度对摩擦力的影响',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 2,
    grade: '八年级',
    tags: ['控制变量', '匀速直线', '弹簧测力计'],
    examLevel: '★★★',
  },
  {
    key: 'pressureEffect',
    name: '探究压力作用效果',
    description: '用海绵凹陷程度比较压力作用效果（转换法）',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 1,
    grade: '八年级',
    tags: ['转换法', '控制变量', '压强'],
    examLevel: '★★',
  },
  {
    key: 'liquidPressure',
    name: '探究液体内部压强',
    description: '用U形管压强计探究液体压强与深度、密度的关系',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 2,
    grade: '八年级',
    tags: ['U形管', '深度', '液体密度'],
    examLevel: '★★',
  },
  {
    key: 'pascalPrinciple',
    name: '帕斯卡原理',
    description: '密闭液体上的压强大小不变地向各个方向传递，液压机原理',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 2,
    grade: '八年级',
    tags: ['帕斯卡原理', '液压机', 'F₁/S₁=F₂/S₂'],
    examLevel: '★★',
  },
  {
    key: 'atmosphericPressure',
    name: '大气压强',
    description: '托里拆利实验、马德堡半球、标准大气压',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 2,
    grade: '八年级',
    tags: ['托里拆利', '760mmHg', '标准大气压', '马德堡半球'],
    examLevel: '★★★',
  },
  {
    key: 'bernoulliPrinciple',
    name: '流体压强与流速关系',
    description: '流速越大的位置压强越小，飞机升力原理',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 1,
    grade: '八年级',
    tags: ['伯努利', '流速', '压强', '飞机升力'],
    examLevel: '★★',
  },
  {
    key: 'archimedesPrinciple',
    name: '探究浮力与排开液体重力',
    description: '验证阿基米德原理：F浮=G排',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 3,
    grade: '九年级',
    tags: ['阿基米德', '称重法', '步骤排序'],
    examLevel: '★★★',
  },
  {
    key: 'buoyancyFactors',
    name: '探究浮力大小与哪些因素有关',
    description: '控制变量法探究液体密度和排开液体体积对浮力的影响',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 2,
    grade: '九年级',
    tags: ['控制变量', '浮力因素', 'ρ液', 'V排'],
    examLevel: '★★★',
  },
  {
    key: 'floatSink',
    name: '物体的浮沉条件',
    description: '探究漂浮、悬浮、下沉的条件：比较物体密度与液体密度',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 2,
    grade: '九年级',
    tags: ['漂浮', '悬浮', '下沉', '密度比较'],
    examLevel: '★★★',
  },
  {
    key: 'leverBalance',
    name: '探究杠杆平衡条件',
    description: '探究动力×动力臂=阻力×阻力臂',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 2,
    grade: '九年级',
    tags: ['杠杆', '力臂', 'F₁L₁=F₂L₂'],
    examLevel: '★★★',
  },
  {
    key: 'pulleyEfficiency',
    name: '测量滑轮组机械效率',
    description: '测量滑轮组的机械效率，分析影响效率的因素',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 2,
    grade: '九年级',
    tags: ['滑轮组', '机械效率', 'η=W有用/W总'],
    examLevel: '★★',
  },

  // ==================== 初中·电学（7个）====================
  {
    key: 'simpleCircuit',
    name: '简单电路',
    description: '电池→开关→灯泡，认识电路的基本组成（通路/断路/短路）',
    category: 'electric',
    subCategory: '初中电学',
    difficulty: 1,
    grade: '九年级',
    tags: ['电路基础', '通路/断路'],
    examLevel: '★★',
    preset: 'simpleCircuit',
  },
  {
    key: 'seriesParallel',
    name: '串并联电路规律',
    description: '探究串联电路电流规律和并联电路电压规律',
    category: 'electric',
    subCategory: '初中电学',
    difficulty: 2,
    grade: '九年级',
    tags: ['串联I₁=I₂', '并联U₁=U₂', '电流表', '电压表'],
    examLevel: '★★',
    preset: 'seriesCircuit',
  },
  {
    key: 'ohmsLaw',
    name: '探究电流与电压、电阻的关系',
    description: '控制变量法：保持R不变改变U，保持U不变改变R，验证I=U/R',
    category: 'electric',
    subCategory: '初中电学',
    difficulty: 2,
    grade: '九年级',
    tags: ['欧姆定律', '控制变量', '滑动变阻器', 'I-V曲线'],
    examLevel: '★★★',
    quickCircuit: true,
  },
  {
    key: 'voltAmpereResistor',
    name: '伏安法测定值电阻',
    description: '用电流表和电压表测量未知电阻，多次测量求平均值',
    category: 'electric',
    subCategory: '初中电学',
    difficulty: 2,
    grade: '九年级',
    tags: ['伏安法', 'R=U/I', '多次测量'],
    examLevel: '★★★',
    preset: 'voltAmpereMethod',
  },
  {
    key: 'bulbPower',
    name: '伏安法测小灯泡电功率',
    description: '测量小灯泡在不同电压下的功率，不能求平均值',
    category: 'electric',
    subCategory: '初中电学',
    difficulty: 3,
    grade: '九年级',
    tags: ['P=UI', '额定功率', '实际功率', '非线性'],
    examLevel: '★★★',
    preset: 'rheostatCurrentLimit',
  },
  {
    key: 'jouleLaw',
    name: '探究焦耳定律',
    description: '探究电流产生的热量与电流、电阻、通电时间的关系',
    category: 'electric',
    subCategory: '初中电学',
    difficulty: 2,
    grade: '九年级',
    tags: ['Q=I²Rt', '转换法', '控制变量'],
    examLevel: '★★',
    comingSoon: true,
  },
  {
    key: 'electromagnet',
    name: '电磁铁磁性影响因素',
    description: '探究匝数和电流大小对电磁铁磁性强弱的影响',
    category: 'electric',
    subCategory: '初中电学',
    difficulty: 1,
    grade: '九年级',
    tags: ['奥斯特实验', '电磁铁', '控制变量'],
    examLevel: '★★',
    comingSoon: true,
  },

  // ==================== 初中·热学（3个）====================
  {
    key: 'meltingCurve',
    name: '探究固体熔化特点',
    description: '水浴加热，绘制温度-时间图像，区分晶体和非晶体',
    category: 'thermal',
    subCategory: '初中热学',
    difficulty: 2,
    grade: '八年级',
    tags: ['水浴加热', '熔点', '晶体/非晶体'],
    examLevel: '★★',
    comingSoon: true,
  },
  {
    key: 'boilingWater',
    name: '探究水的沸腾',
    description: '观察沸腾现象，绘制温度-时间图像，沸点与气压关系',
    category: 'thermal',
    subCategory: '初中热学',
    difficulty: 1,
    grade: '八年级',
    tags: ['沸点', '气泡变化', '气压'],
    examLevel: '★★',
    comingSoon: true,
  },
  {
    key: 'specificHeat',
    name: '探究不同物质吸热能力',
    description: '用相同加热器比较不同物质的升温快慢（比热容）',
    category: 'thermal',
    subCategory: '初中热学',
    difficulty: 2,
    grade: '九年级',
    tags: ['比热容', '控制变量', '转换法'],
    examLevel: '★★',
    comingSoon: true,
  },

  // ==================== 初中·光学（3个）====================
  {
    key: 'reflectionLaw',
    name: '光的反射定律',
    description: '用纸板验证反射光线、入射光线和法线共面',
    category: 'optics',
    subCategory: '初中光学',
    difficulty: 1,
    grade: '八年级',
    tags: ['反射定律', '法线', '共面'],
    examLevel: '★★',
    preset: 'mirrorReflection',
  },
  {
    key: 'planeMirrorImage',
    name: '平面镜成像特点',
    description: '用玻璃板和等大蜡烛探究：像距=物距，像与物等大',
    category: 'optics',
    subCategory: '初中光学',
    difficulty: 2,
    grade: '八年级',
    tags: ['玻璃板', '等大蜡烛', '虚像', '等距'],
    examLevel: '★★★',
  },
  {
    key: 'convexLensImaging',
    name: '凸透镜成像规律',
    description: '探究物距变化时像距、像大小的变化规律',
    category: 'optics',
    subCategory: '初中光学',
    difficulty: 3,
    grade: '八年级',
    tags: ['凸透镜', '实像/虚像', '三心同高', '1/u+1/v=1/f'],
    examLevel: '★★★',
    preset: 'convexLensImaging',
  },

  // ==================== 初中·声学（1个）====================
  {
    key: 'concaveLensImaging',
    name: '凹透镜成像规律',
    description: '探究凹透镜成像特点：永远生成正立缩小虚像',
    category: 'optics',
    subCategory: '初中光学',
    difficulty: 2,
    grade: '八年级',
    tags: ['凹透镜', '虚像', '正立缩小', '发散透镜'],
    examLevel: '★★',
  },
  // ==================== 声学·声波基础 ====================
  {
    key: 'soundWave',
    name: '声波可视化与发声',
    description: '实时波形+频谱+拍频，Web Audio发声，频率/波形/音量可调',
    category: 'sound',
    subCategory: '声学基础',
    difficulty: 1,
    grade: '八年级',
    tags: ['声波', '波形', '频谱', '拍频', '频率', '发声'],
    examLevel: '★',
  },
  {
    key: 'soundPropagation',
    name: '声音的产生与传播',
    description: '真空铃实验（推理法）、介质声速对比（空气/水/钢铁）',
    category: 'sound',
    subCategory: '初中声学',
    difficulty: 1,
    grade: '八年级',
    tags: ['真空铃', '传播', '介质', '声速'],
    examLevel: '★',
  },
  {
    key: 'soundPitch',
    name: '音调与频率',
    description: '频率↑音调↑，听觉范围20~20000Hz，音阶频率预设',
    category: 'sound',
    subCategory: '初中声学',
    difficulty: 1,
    grade: '八年级',
    tags: ['音调', '频率', '听觉范围', '音阶'],
    examLevel: '★',
  },
  {
    key: 'soundLoudness',
    name: '响度与振幅',
    description: '振幅↑响度↑，固定频率改变音量，波形振幅实时变化',
    category: 'sound',
    subCategory: '初中声学',
    difficulty: 1,
    grade: '八年级',
    tags: ['响度', '振幅', '分贝', '音量'],
    examLevel: '★',
  },
  {
    key: 'soundTimbre',
    name: '音色与波形',
    description: '四种波形音色对比，谐波结构分析，频谱展示',
    category: 'sound',
    subCategory: '初中声学',
    difficulty: 2,
    grade: '八年级',
    tags: ['音色', '波形', '谐波', '正弦', '方波', '三角', '锯齿'],
    examLevel: '★★',
  },
  {
    key: 'soundBasics',
    name: '声音的产生与传播',
    description: '真空铃实验（推理法）、音调与频率、响度与振幅',
    category: 'sound',
    subCategory: '初中声学',
    difficulty: 1,
    grade: '八年级',
    tags: ['真空铃', '频率', '振幅', '音色'],
    examLevel: '★',
    comingSoon: true,
  },

  // ==================== 高中·力学（7个）====================
  {
    key: 'uniformAccel',
    name: '研究匀变速直线运动',
    description: '打点计时器纸带实验：求瞬时速度、逐差法求加速度',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 3,
    grade: '高一',
    tags: ['打点计时器', '逐差法', 'v-t图像'],
    examLevel: '★★★',
  },
  {
    key: 'springForce',
    name: '探究弹力和弹簧伸长关系',
    description: '绘制F-x图像，求劲度系数k',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 2,
    grade: '高一',
    tags: ['胡克定律', 'F=kx', '劲度系数'],
    examLevel: '★★',
  },
  {
    key: 'hookeLaw',
    name: '探究胡克定律（NB+PhET融合版）',
    description: '融合NB测力计表盘+PhET矢量可视化，数据表格+F-Δx拟合+CSV导出',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 2,
    grade: '高一',
    tags: ['胡克定律', 'NB测力计', 'F-Δx拟合', '数据导出'],
    examLevel: '★★★',
    beyondCurriculum: true,
    beyondReason: '标准胡克定律实验的增强版，NB测力计表盘+矢量可视化+CSV导出+R²拟合超出课标要求',
  },
  {
    key: 'parallelogramRule',
    name: '验证力的平行四边形定则',
    description: '等效替代法验证力的合成规则',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 2,
    grade: '高一',
    tags: ['等效替代', '合力', '分力'],
    examLevel: '★★',
  },
  {
    key: 'newtonSecondLaw',
    name: '验证牛顿第二定律',
    description: 'F=ma：控制质量不变改变力，控制力不变改变质量',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 3,
    grade: '高一',
    tags: ['F=ma', '平衡摩擦力', '砂桶质量≪小车质量'],
    examLevel: '★★★',
  },
  {
    key: 'projectileMotion',
    name: '探究平抛运动规律',
    description: '描迹法：水平匀速+竖直自由落体分解',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 2,
    grade: '高一',
    tags: ['平抛', '运动分解', '轨迹'],
    examLevel: '★★',
  },
  {
    key: 'energyConservation',
    name: '验证机械能守恒定律',
    description: '纸带实验：不需要测质量，比较动能增量和势能减少量',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 3,
    grade: '高一',
    tags: ['机械能守恒', '纸带', '阻力误差'],
    examLevel: '★★★',
  },
  {
    key: 'collisionLab',
    name: '碰撞实验室',
    description: 'PhET风格一维碰撞仿真：弹性/非弹性碰撞，拖拽交互，动量动能实时显示',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 3,
    grade: '高一',
    tags: ['动量守恒', '弹性碰撞', '恢复系数', 'PhET'],
    examLevel: '★★★',
    beyondCurriculum: true,
    beyondReason: '恢复系数+弹性/非弹性碰撞定量仿真超出课标，课标仅要求定性了解动量守恒',
  },
  {
    key: 'momentumConservation',
    name: '探究动量守恒定律',
    description: '斜槽平抛方案或气垫导轨方案',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 3,
    grade: '高一',
    tags: ['动量守恒', '碰撞', '气垫导轨'],
    examLevel: '★★★',
  },
  {
    key: 'newtonFirstLaw',
    name: '牛顿第一定律（惯性定律）',
    description: '理想斜面实验：物体不受力时保持静止或匀速直线运动，推理法得出惯性定律',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 2,
    grade: '高一',
    tags: ['惯性', '理想斜面', '推理法', '伽利略'],
    examLevel: '★★★',
    beyondCurriculum: true,
    beyondReason: '伽利略理想斜面实验还原+摩擦系数调节仿真超出课标，课标仅要求理解惯性定律结论',
  },
  {
    key: 'newtonThirdLaw',
    name: '牛顿第三定律（作用力与反作用力）',
    description: '弹簧测力计对拉、小车碰撞、磁铁互吸三种方案验证F₁=-F₂',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 2,
    grade: '高一',
    tags: ['作用力', '反作用力', '等大反向', '弹簧测力计'],
    examLevel: '★★★',
  },
  {
    key: 'circularMotion',
    name: '圆周运动与向心力',
    description: '控制变量法探究向心力F=mv²/r，验证F∝v²、F∝1/r、F∝m',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 3,
    grade: '高一',
    tags: ['向心力', 'F=mv²/r', '角速度', '周期', '控制变量'],
    examLevel: '★★★',
    beyondCurriculum: true,
    beyondReason: '三模式控制变量法定量验证（F∝v²/F∝1/r/F∝m）超出课标，属于竞赛级实验深度',
  },
  {
    key: 'galileoFreeFall',
    name: '伽利略自由落体实验',
    description: '轻重物体同时落地验证、斜面冲淡重力实验、s-t²图像验证s∝t²',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 2,
    grade: '高一',
    tags: ['自由落体', 's=½gt²', '斜面实验', '伽利略', '推理法'],
    examLevel: '★★★',
    beyondCurriculum: true,
    beyondReason: '斜面冲淡重力历史实验还原+s-t²图像验证超出课标，课标仅要求了解自由落体规律',
  },
  {
    key: 'keplerLaws',
    name: '开普勒三大定律',
    description: '椭圆轨道、面积定律、T²∝a³，行星运动动画仿真',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 2,
    grade: '高一',
    tags: ['开普勒', '椭圆轨道', '面积定律', 'T²∝a³', '行星运动'],
    examLevel: '★★★',
    beyondCurriculum: true,
    beyondReason: '椭圆轨道+面积定律+T²∝a³定量仿真超出课标，课标仅要求定性了解行星运动规律',
  },
  {
    key: 'universalGravitation',
    name: '万有引力定律',
    description: 'F=GMm/r²，距离关系、质量关系、卡文迪什扭秤实验',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 2,
    grade: '高一',
    tags: ['万有引力', 'F=GMm/r²', '引力常数G', '卡文迪什', '平方反比'],
    examLevel: '★★★',
    beyondCurriculum: true,
    beyondReason: '卡文迪什扭秤仿真+三模式定量验证超出课标，课标仅要求掌握公式应用',
  },
  {
    key: 'cosmicVelocity',
    name: '三大宇宙速度与同步卫星',
    description: 'v₁=7.9km/s环绕、v₂=11.2km/s逃逸、v₃=16.7km/s飞出太阳系、同步卫星推导',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 3,
    grade: '高一',
    tags: ['宇宙速度', '环绕速度', '逃逸速度', '同步卫星', 'T=24h'],
    examLevel: '★★★',
    beyondCurriculum: true,
    beyondReason: 'v₂/v₃推导+同步卫星轨道仿真超出课标，课标仅要求知道第一宇宙速度',
  },
  {
    key: 'rocket',
    name: '运载火箭工作原理',
    description: '变质量系统推力模型、齐奥尔科夫斯基公式、多级火箭分离、发射动画仿真',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 3,
    grade: '高一',
    tags: ['火箭推力', '变质量', '齐奥尔科夫斯基', '多级分离', '动量守恒'],
    examLevel: '★',
    beyondCurriculum: true,
    beyondReason: '变质量系统+齐奥尔科夫斯基火箭方程+多级分离属于航天工程内容，超出中学物理课标',
  },

  // ==================== 高中·电磁学（6个）====================
  {
    key: 'voltAmpereMethodHS',
    name: '伏安法测电阻（内接/外接）',
    description: '根据待测电阻阻值选择电流表内接法或外接法',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 3,
    grade: '高二',
    tags: ['内接法', '外接法', '系统误差'],
    examLevel: '★★★',
    preset: 'voltAmpereMethod',
  },
  {
    key: 'bulbIVCurve',
    name: '测绘小灯泡伏安特性曲线',
    description: '分压式接法，绘制I-V曲线，分析非线性原因',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 3,
    grade: '高二',
    tags: ['分压式', '伏安特性', '非线性', '温度影响'],
    examLevel: '★★★',
    preset: 'rheostatCurrentLimit',
  },
  {
    key: 'emfInternalResistance',
    name: '测量电源电动势和内阻',
    description: '两种电路方案，分析系统误差来源',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 3,
    grade: '高二',
    tags: ['电动势', '内阻', 'U-I图像', '系统误差'],
    examLevel: '★★★',
    comingSoon: true,
  },
  {
    key: 'multimeter',
    name: '练习使用多用电表',
    description: '欧姆调零、档位选择、二极管测量',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 2,
    grade: '高二',
    tags: ['多用电表', '欧姆档', '二极管'],
    examLevel: '★★',
    comingSoon: true,
  },
  {
    key: 'ampereForce',
    name: '探究安培力影响因素',
    description: '探究电流大小、导线长度、磁场强弱对安培力的影响',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 2,
    grade: '高二',
    tags: ['安培力', 'F=BIL', '左手定则'],
    examLevel: '★',
    comingSoon: true,
  },
  {
    key: 'lenzLaw',
    name: '楞次定律探究',
    description: '探究感应电流的方向：来拒去留',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 2,
    grade: '高二',
    tags: ['楞次定律', '感应电流', '磁通量变化'],
    examLevel: '★★',
    comingSoon: true,
  },

  // ==================== 高中·热学（1个）====================
  {
    key: 'oilFilmMethod',
    name: '用油膜法估测分子大小',
    description: '单分子油膜模型：d=V/S',
    category: 'thermal',
    subCategory: '高中热学',
    difficulty: 2,
    grade: '高二',
    tags: ['油膜法', '分子大小', '模型法'],
    examLevel: '★★',
    comingSoon: true,
  },

  // ==================== 高中·光学（3个）====================
  {
    key: 'glassRefraction',
    name: '测定玻璃折射率',
    description: '插针法确定光路，测量入射角和折射角',
    category: 'optics',
    subCategory: '高中光学',
    difficulty: 2,
    grade: '高二',
    tags: ['插针法', '折射率', 'n=sin i/sin r'],
    examLevel: '★★',
  },

  // ==================== 高中·光学（新增2个）====================
  {
    key: 'interferenceDiffraction',
    name: '光的干涉与衍射',
    description: '双缝干涉与单缝衍射实验，观察干涉条纹和衍射图样',
    category: 'optics',
    subCategory: '高中光学',
    difficulty: 3,
    grade: '高二',
    tags: ['双缝干涉', '单缝衍射', '明暗条纹', 'Δy=λL/d'],
    examLevel: '★★★',
    beyondCurriculum: true,
    beyondReason: '单缝衍射光强分布曲线+三种模式切换超出课标，课标仅要求定性观察干涉衍射现象',
  },
  {
    key: 'prismDispersion',
    name: '三棱镜色散',
    description: '白光通过三棱镜分散成七色光谱，探究色散规律',
    category: 'optics',
    subCategory: '高中光学',
    difficulty: 2,
    grade: '高二',
    tags: ['色散', '光谱', '折射率', 'n(λ)=n₀+B/λ²'],
    examLevel: '★★',
    beyondCurriculum: true,
    beyondReason: '柯西色散公式n(λ)=n₀+B/λ²+全内反射计算超出课标，课标仅要求定性了解色散现象',
  },

  // ==================== 高中·近代物理（1个）====================
  {
    key: 'photoelectric',
    name: '光电效应现象认识',
    description: '认识光电效应实验规律，了解光子说解释',
    category: 'modern',
    subCategory: '高中近代物理',
    difficulty: 2,
    grade: '高二',
    tags: ['光电效应', '光子', '截止频率', '最大初动能'],
    examLevel: '★',
    comingSoon: true,
  },
]

/** 分类配置 */
export const CATEGORIES = [
  { key: 'mechanics', name: '力学', icon: '⚙️', color: '#FF9800' },
  { key: 'electric', name: '电学', icon: '⚡', color: '#4CAF50' },
  { key: 'thermal', name: '热学', icon: '🌡️', color: '#f44336' },
  { key: 'optics', name: '光学', icon: '🔬', color: '#2196F3' },
  { key: 'sound', name: '声学', icon: '🔊', color: '#9C27B0' },
  { key: 'modern', name: '近代物理', icon: '⚛️', color: '#607D8B' },
]

/** 难度标签 */
export const DIFFICULTY_LABELS = ['', '⭐ 基础', '⭐⭐ 提高', '⭐⭐⭐ 挑战']

/** 超纲实验列表 */
export const BEYOND_CURRICULUM = EXPERIMENT_CATALOG
  .filter(e => e.beyondCurriculum)
  .map(e => ({ key: e.key, name: e.name, reason: e.beyondReason }))

/** 考试等级说明 */
export const EXAM_LEVEL_DESC = {
  '★★★': '必考核心实验',
  '★★': '高频实验',
  '★': '了解类实验',
}
