/**
 * 实验目录 — 按物理课标体系完整覆盖
 *
 * 初中：力学·电学·热学·光学·声学（五大板块）
 * 高中：力学·电磁学·热学·光学·近代物理
 *
 * 难度：★基础  ★★提高  ★★★挑战
 * 标记：★★★必考核心  ★★高频  ★了解
 * 超纲：beyondCurriculum=true 表示超出中学物理课标要求，仅供拓展/竞赛参考
 */

export const EXPERIMENT_CATALOG = [
  // ==================== 初中·力学（8个）====================
  {
    key: 'measureSpeed',
    name: '测量平均速度',
    description: '用刻度尺和秒表测量物体沿斜面运动的平均速度',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 1,
    grade: '八年级',
    tags: ['刻度尺', '秒表', 'v=s/t'],
    examLevel: '★★',
  },
  {
    key: 'densityMeasurement',
    name: '测量物质密度',
    description: '用天平和量筒测量固体和液体的密度',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 2,
    grade: '八年级',
    tags: ['天平', '量筒', 'ρ=m/V', '误差分析'],
    examLevel: '★★★',
  },
  {
    key: 'frictionForce',
    name: '探究滑动摩擦力影响因素',
    description: '控制变量法探究压力和接触面粗糙程度对摩擦力的影响',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 2,
    grade: '八年级',
    tags: ['控制变量', '匀速直线', '弹簧测力计'],
    examLevel: '★★★',
  },
  {
    key: 'pressureEffect',
    name: '探究压力作用效果',
    description: '用海绵凹陷程度比较压力作用效果（转换法）',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 1,
    grade: '八年级',
    tags: ['转换法', '控制变量', '压强'],
    examLevel: '★★',
  },
  {
    key: 'liquidPressure',
    name: '探究液体内部压强',
    description: '用U形管压强计探究液体压强与深度、密度的关系',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 2,
    grade: '八年级',
    tags: ['U形管', '深度', '液体密度'],
    examLevel: '★★',
  },
  {
    key: 'pascalPrinciple',
    name: '帕斯卡原理',
    description: '密闭液体上的压强大小不变地向各个方向传递，液压机原理',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 2,
    grade: '八年级',
    tags: ['帕斯卡原理', '液压机', 'F₁/S₁=F₂/S₂'],
    examLevel: '★★',
  },
  {
    key: 'atmosphericPressure',
    name: '大气压强',
    description: '托里拆利实验、马德堡半球、标准大气压',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 2,
    grade: '八年级',
    tags: ['托里拆利', '760mmHg', '标准大气压', '马德堡半球'],
    examLevel: '★★★',
  },
  {
    key: 'bernoulliPrinciple',
    name: '流体压强与流速关系',
    description: '流速越大的位置压强越小，飞机升力原理',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 1,
    grade: '八年级',
    tags: ['伯努利', '流速', '压强', '飞机升力'],
    examLevel: '★★',
  },
  {
    key: 'archimedesPrinciple',
    name: '浮力综合实验',
    description: '控制变量法探究浮力因素（ρ液、V排）+ 验证阿基米德原理F浮=G排',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 3,
    grade: '九年级',
    tags: ['阿基米德', '称重法', '步骤排序'],
    examLevel: '★★★',
  },

  {
    key: 'floatSink',
    name: '物体的浮沉条件',
    description: '探究漂浮、悬浮、下沉的条件：比较物体密度与液体密度',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 2,
    grade: '九年级',
    tags: ['漂浮', '悬浮', '下沉', '密度比较'],
    examLevel: '★★★',
  },
  {
    key: 'leverBalance',
    name: '探究杠杆平衡条件',
    description: '探究动力×动力臂=阻力×阻力臂',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 2,
    grade: '九年级',
    tags: ['杠杆', '力臂', 'F₁L₁=F₂L₂'],
    examLevel: '★★★',
  },
  {
    key: 'pulleyEfficiency',
    name: '测量滑轮组机械效率',
    description: '测量滑轮组的机械效率，分析影响效率的因素',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 2,
    grade: '九年级',
    tags: ['滑轮组', '机械效率', 'η=W有用/W总'],
    examLevel: '★★',
  },

  // ==================== 初中·电学（7个）====================
  {
    key: 'simpleCircuit',
    name: '简单电路',
    description: '电池→开关→灯泡，认识电路的基本组成（通路/断路/短路）',
    category: 'electric',
    subCategory: '初中电学',
    difficulty: 1,
    grade: '九年级',
    tags: ['电路基础', '通路/断路'],
    examLevel: '★★',
    preset: 'simpleCircuit',
  },
  {
    key: 'seriesParallel',
    name: '串并联电路规律',
    description: '探究串联电路电流规律和并联电路电压规律',
    category: 'electric',
    subCategory: '初中电学',
    difficulty: 2,
    grade: '九年级',
    tags: ['串联I₁=I₂', '并联U₁=U₂', '电流表', '电压表'],
    examLevel: '★★',
    preset: 'seriesCircuit',
  },
  {
    key: 'ohmsLaw',
    name: '探究电流与电压、电阻的关系',
    description: '控制变量法：保持R不变改变U，保持U不变改变R，验证I=U/R',
    category: 'electric',
    subCategory: '初中电学',
    difficulty: 2,
    grade: '九年级',
    tags: ['欧姆定律', '控制变量', '滑动变阻器', 'I-V曲线'],
    examLevel: '★★★',
    quickCircuit: true,
  },
  {
    key: 'voltAmpereResistor',
    name: '伏安法测定值电阻',
    description: '用电流表和电压表测量未知电阻，多次测量求平均值（初中基础版；内接/外接系统误差分析见高中版）',
    category: 'electric',
    subCategory: '初中电学',
    difficulty: 2,
    grade: '九年级',
    tags: ['伏安法', 'R=U/I', '多次测量'],
    examLevel: '★★★',
    preset: 'voltAmpereMethod',
  },
  {
    key: 'bulbPower',
    name: '伏安法测小灯泡电功率',
    description: '测量小灯泡在不同电压下的功率，不能求平均值（初中版；伏安特性曲线分析见高中版）',
    category: 'electric',
    subCategory: '初中电学',
    difficulty: 3,
    grade: '九年级',
    tags: ['P=UI', '额定功率', '实际功率', '非线性'],
    examLevel: '★★★',
    preset: 'rheostatCurrentLimit',
  },
  {
    key: 'jouleLaw',
    name: '探究焦耳定律',
    description: '探究电流产生的热量与电流、电阻、通电时间的关系',
    category: 'electric',
    subCategory: '初中电学',
    difficulty: 2,
    grade: '九年级',
    tags: ['Q=I²Rt', '转换法', '控制变量'],
    examLevel: '★★',
  },
  {
    key: 'electromagnet',
    name: '电磁铁磁性影响因素',
    description: '探究匝数和电流大小对电磁铁磁性强弱的影响',
    category: 'electric',
    subCategory: '初中电学',
    difficulty: 1,
    grade: '九年级',
    tags: ['奥斯特实验', '电磁铁', '控制变量'],
    examLevel: '★★',
  },
  {
    key: 'electricEnergy',
    name: '电功与电能表',
    description: '认识电能表、计算电费、理解电功 W=UIt',
    category: 'electric',
    subCategory: '初中电学',
    difficulty: 1,
    grade: '九年级',
    tags: ['电功', '电能表', 'W=UIt', '千瓦时'],
    examLevel: '★★',
  },
  {
    key: 'ostersExperiment',
    name: '电生磁（奥斯特实验）',
    description: '通电导线周围产生磁场，电流方向与磁针偏转方向的关系',
    category: 'electric',
    subCategory: '初中电学',
    difficulty: 1,
    grade: '九年级',
    tags: ['奥斯特', '电生磁', '安培定则'],
    examLevel: '★★',
  },
  {
    key: 'electricMotor',
    name: '电动机原理',
    description: '通电线圈在磁场中受力转动，理解换向器的作用',
    category: 'electric',
    subCategory: '初中电学',
    difficulty: 2,
    grade: '九年级',
    tags: ['电动机', '安培力', '换向器', '左手定则'],
    examLevel: '★★',
  },
  {
    key: 'electromagneticInduction',
    name: '电磁感应（法拉第实验）',
    description: '磁生电：导体切割磁感线产生感应电流',
    category: 'electric',
    subCategory: '初中电学',
    difficulty: 2,
    grade: '九年级',
    tags: ['法拉第', '磁生电', '感应电流', '发电机'],
    examLevel: '★★',
  },

  // ==================== 热学 · 八年级基础 ====================
  {
    key: 'meltingCurve',
    name: '探究固体熔化特点',
    description: '水浴加热晶体与非晶体，实时绘制温度-时间曲线，观察熔点与熔化过程',
    category: 'thermal',
    subCategory: '八年级基础',
    difficulty: 2,
    grade: '八年级',
    tags: ['水浴加热', '熔点', '晶体', '非晶体', '熔化曲线'],
    examLevel: '★★',
  },
  {
    key: 'boilingWater',
    name: '探究水的沸腾',
    description: '观察沸腾现象，绘制温度-时间图像，探究沸点与气压的关系',
    category: 'thermal',
    subCategory: '八年级基础',
    difficulty: 1,
    grade: '八年级',
    tags: ['沸点', '气泡', '气压', '沸腾曲线'],
    examLevel: '★★',
  },
  {
    key: 'specificHeat',
    name: '探究不同物质吸热能力',
    description: '用相同加热器比较不同物质的升温快慢，建立比热容概念，验证 Q=cmΔt',
    category: 'thermal',
    subCategory: '八年级基础',
    difficulty: 2,
    grade: '九年级',
    tags: ['比热容', '控制变量', '转换法', 'Q=cmΔt'],
    examLevel: '★★',
  },
  {
    key: 'brownianMotion',
    name: '布朗运动模拟',
    description: '模拟花粉颗粒受水分子碰撞的随机运动，观察温度越高运动越剧烈，理解分子热运动',
    category: 'thermal',
    subCategory: '八年级基础',
    difficulty: 1,
    grade: '九年级',
    tags: ['布朗运动', '分子运动', '温度', '随机运动'],
    examLevel: '★',
  },
  {
    key: 'diffusion',
    name: '扩散现象与分子热运动',
    description: '两种气体/液体混合扩散，调节温度观察扩散速率变化，理解分子永不停息的无规则运动',
    category: 'thermal',
    subCategory: '八年级基础',
    difficulty: 1,
    grade: '九年级',
    tags: ['扩散', '分子运动', '温度', '气液固'],
    examLevel: '★★',
  },
  {
    key: 'evaporation',
    name: '探究蒸发快慢的影响因素',
    description: '控制变量法探究液体温度、表面积、空气流速、液体种类对蒸发快慢的影响',
    category: 'thermal',
    subCategory: '八年级基础',
    difficulty: 1,
    grade: '八年级',
    tags: ['蒸发', '控制变量', '表面积', '温度', '空气流速'],
    examLevel: '★★',
  },
  {
    key: 'phaseChange',
    name: '物态变化综合',
    description: '熔化/凝固、汽化/液化、升华/凝华六种物态变化全景，温度-时间曲线，吸放热标注',
    category: 'thermal',
    subCategory: '八年级基础',
    difficulty: 2,
    grade: '八年级',
    tags: ['物态变化', '熔化', '凝固', '汽化', '液化', '升华', '凝华'],
    examLevel: '★★',
  },
  // ==================== 热学 · 高中提高 ====================
  {
    key: 'oilFilmMethod',
    name: '用油膜法估测分子大小',
    description: '单分子油膜模型，滴油扩散，计算油膜面积，估测分子直径 d=V/S',
    category: 'thermal',
    subCategory: '高中提高',
    difficulty: 2,
    grade: '高二',
    tags: ['油膜法', '分子大小', '模型法', 'd=V/S'],
    examLevel: '★★',
  },
  {
    key: 'gasLaws',
    name: '气体实验定律',
    description: '探究玻意耳定律、查理定律、盖-吕萨克定律，绘制p-V/T图像，理解理想气体模型',
    category: 'thermal',
    subCategory: '高中提高',
    difficulty: 3,
    grade: '高二',
    tags: ['玻意耳', '查理', '盖-吕萨克', 'pV=nRT', '理想气体'],
    examLevel: '★★★',
  },
  {
    key: 'thermodynamicsFirst',
    name: '热力学第一定律',
    description: '探究做功与热传递改变内能，验证 ΔU=Q+W，分析等温/等压/等容过程',
    category: 'thermal',
    subCategory: '高中提高',
    difficulty: 3,
    grade: '高二',
    tags: ['热力学', '内能', '做功', '热传递', 'ΔU=Q+W'],
    examLevel: '★★★',
  },
  // ==================== 热学 · 高中挑战 ====================
  {
    key: 'carnotEngine',
    name: '卡诺循环与热机效率',
    description: '模拟卡诺循环四过程，计算热机效率，理解热力学第二定律与熵增原理',
    category: 'thermal',
    subCategory: '高中挑战',
    difficulty: 3,
    grade: '高二',
    tags: ['卡诺循环', '热机效率', '热力学第二定律', '熵增'],
    examLevel: '★★★',
  },

  // ==================== 初中·光学（3个）====================
  {
    key: 'reflectionLaw',
    name: '光的反射定律',
    description: '用纸板验证反射光线、入射光线和法线共面',
    category: 'optics',
    subCategory: '初中光学',
    difficulty: 1,
    grade: '八年级',
    tags: ['反射定律', '法线', '共面'],
    examLevel: '★★',
    preset: 'mirrorReflection',
  },
  {
    key: 'planeMirrorImage',
    name: '平面镜成像特点',
    description: '用玻璃板和等大蜡烛探究：像距=物距，像与物等大',
    category: 'optics',
    subCategory: '初中光学',
    difficulty: 2,
    grade: '八年级',
    tags: ['玻璃板', '等大蜡烛', '虚像', '等距'],
    examLevel: '★★★',
  },
  {
    key: 'convexLensImaging',
    name: '凸透镜成像规律',
    description: '探究物距变化时像距、像大小的变化规律',
    category: 'optics',
    subCategory: '初中光学',
    difficulty: 3,
    grade: '八年级',
    tags: ['凸透镜', '实像/虚像', '三心同高', '1/u+1/v=1/f'],
    examLevel: '★★★',
    preset: 'convexLensImaging',
  },

  // ==================== 初中·声学（1个）====================
  {
    key: 'concaveLensImaging',
    name: '凹透镜成像规律',
    description: '探究凹透镜成像特点：永远生成正立缩小虚像',
    category: 'optics',
    subCategory: '初中光学',
    difficulty: 2,
    grade: '八年级',
    tags: ['凹透镜', '虚像', '正立缩小', '发散透镜'],
    examLevel: '★★',
  },
  {
    key: 'refractionLaw',
    name: '光的折射定律',
    description: '探究光从空气进入水/玻璃时入射角与折射角的关系，理解折射规律',
    category: 'optics',
    subCategory: '初中光学',
    difficulty: 2,
    grade: '八年级',
    tags: ['折射定律', '入射角', '折射角', '折射率'],
    examLevel: '★★',
  },
  // ==================== 声学 · 八年级基础 ====================
  {
    key: 'soundPropagation',
    name: '声音的产生与传播',
    description: '探究真空铃实验（推理法），对比固体/液体/气体三种介质中的声速差异，理解声音传播需要介质',
    category: 'sound',
    subCategory: '八年级基础',
    difficulty: 1,
    grade: '八年级',
    tags: ['真空铃', '传播', '介质', '声速'],
    examLevel: '★',
  },
  {
    key: 'soundWave',
    name: '声波可视化与发声',
    description: '实时观察正弦/方波/三角/锯齿波形与频谱，探究频率与音调、振幅与响度、波形与音色的关系',
    category: 'sound',
    subCategory: '八年级基础',
    difficulty: 1,
    grade: '八年级',
    tags: ['声波', '波形', '频谱', '频率', '发声', '音调', '响度', '音色'],
    examLevel: '★',
  },
  {
    key: 'soundNoise',
    name: '噪声的防治',
    description: '模拟不同噪声源，观察声强级dB变化，探究声源处/传播中/接收处三种防治途径',
    category: 'sound',
    subCategory: '八年级基础',
    difficulty: 1,
    grade: '八年级',
    tags: ['噪声', '分贝', 'dB', '防治'],
    examLevel: '★',
  },
  {
    key: 'soundEcho',
    name: '回声与声测距',
    description: '改变声源到障碍物的距离，观察回声时间差，验证回声测距公式 s=vt/2',
    category: 'sound',
    subCategory: '八年级基础',
    difficulty: 1,
    grade: '八年级',
    tags: ['回声', '测距', '反射', '声速'],
    examLevel: '★',
  },
  // ==================== 声学 · 高中提高 ====================
  {
    key: 'soundResonance',
    name: '共振实验',
    description: '调节驱动频率扫描固有频率，观察振幅响应曲线，找到共振峰，理解共振条件与应用',
    category: 'sound',
    subCategory: '高中提高',
    difficulty: 2,
    grade: '高一',
    tags: ['共振', '固有频率', '扫频', '振幅响应'],
    examLevel: '★★',
  },
  {
    key: 'soundString',
    name: '弦振动与驻波',
    description: '调节弦长/张力/线密度，观察基频与各次谐波的驻波形态，探究弦振动频率公式 f=n/(2L)√(T/μ)',
    category: 'sound',
    subCategory: '高中提高',
    difficulty: 3,
    grade: '高一',
    tags: ['驻波', '弦振动', '谐波', '基频', '波节', '波腹'],
    examLevel: '★★★',
  },
  {
    key: 'soundPipe',
    name: '管内驻波',
    description: '对比开管/闭管的共振频率与驻波分布，探究开管含全部谐波、闭管仅含奇次谐波的规律',
    category: 'sound',
    subCategory: '高中提高',
    difficulty: 3,
    grade: '高一',
    tags: ['开管', '闭管', '驻波', '共振', '谐波'],
    examLevel: '★★★',
  },
  // ==================== 声学 · 高中挑战 ====================
  {
    key: 'soundInterference',
    name: '声波干涉',
    description: '两列同频声波叠加，调节相位差观察相长/相消干涉，理解波的叠加原理与拍频现象',
    category: 'sound',
    subCategory: '高中挑战',
    difficulty: 3,
    grade: '高一',
    tags: ['干涉', '相长', '相消', '相位差', '叠加', '拍频'],
    examLevel: '★★★',
  },
  {
    key: 'soundDoppler',
    name: '多普勒效应',
    description: '调节声源速度与方向，观察趋近/远离时接收频率的变化，验证多普勒公式 f′=f·v/(v±vₛ)',
    category: 'sound',
    subCategory: '高中挑战',
    difficulty: 3,
    grade: '高一',
    tags: ['多普勒', '频率变化', '声源移动', '红移'],
    examLevel: '★★★',
  },


  // ==================== 高中·力学（7个）====================
  {
    key: 'uniformAccel',
    name: '研究匀变速直线运动',
    description: '打点计时器纸带实验：求瞬时速度、逐差法求加速度',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 3,
    grade: '高一',
    tags: ['打点计时器', '逐差法', 'v-t图像'],
    examLevel: '★★★',
  },
  {
    key: 'springForce',
    name: '探究弹力和弹簧伸长关系',
    description: '绘制F-x图像，求劲度系数k（基础版；增强版见同名NB+PhET融合版）',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 2,
    grade: '高一',
    tags: ['胡克定律', 'F=kx', '劲度系数'],
    examLevel: '★★',
  },
  {
    key: 'hookeLaw',
    name: '探究胡克定律',
    description: '探究弹簧伸长与拉力的关系，数据表格+F-Δx拟合+CSV导出',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 2,
    grade: '高一',
    tags: ['胡克定律', 'F=kx', 'F-Δx拟合', '数据导出'],
    examLevel: '★★★',
    beyondCurriculum: true,
    beyondReason: '标准胡克定律实验的增强版，矢量可视化+CSV导出+R²拟合超出课标要求',
  },
  {
    key: 'parallelogramRule',
    name: '验证力的平行四边形定则',
    description: '等效替代法验证力的合成规则',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 2,
    grade: '高一',
    tags: ['等效替代', '合力', '分力'],
    examLevel: '★★',
  },
  {
    key: 'newtonSecondLaw',
    name: '验证牛顿第二定律',
    description: 'F=ma：控制质量不变改变力，控制力不变改变质量',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 3,
    grade: '高一',
    tags: ['F=ma', '平衡摩擦力', '砂桶质量≪小车质量'],
    examLevel: '★★★',
  },
  {
    key: 'projectileMotion',
    name: '探究平抛运动规律',
    description: '描迹法：水平匀速+竖直自由落体分解',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 2,
    grade: '高一',
    tags: ['平抛', '运动分解', '轨迹'],
    examLevel: '★★',
  },
  {
    key: 'energyConservation',
    name: '验证机械能守恒定律',
    description: '纸带实验：不需要测质量，比较动能增量和势能减少量',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 3,
    grade: '高一',
    tags: ['机械能守恒', '纸带', '阻力误差'],
    examLevel: '★★★',
  },
  {
    key: 'collisionLab',
    name: '碰撞实验室',
    description: '双模式碰撞仿真：课标基础版（探究动量守恒）+ 增强版（拖拽交互、恢复系数、矢量可视化）',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 3,
    grade: '高一',
    tags: ['动量守恒', '弹性碰撞', '恢复系数', 'PhET', '气垫导轨'],
    examLevel: '★★★',
  },

  {
    key: 'newtonFirstLaw',
    name: '牛顿第一定律（惯性定律）',
    description: '理想斜面实验：物体不受力时保持静止或匀速直线运动，推理法得出惯性定律',
    category: 'mechanics',
    subCategory: '初中力学',
    difficulty: 2,
    grade: '八年级',
    tags: ['惯性', '理想斜面', '推理法', '伽利略'],
    examLevel: '★★★',
    beyondCurriculum: true,
    beyondReason: '伽利略理想斜面实验还原+摩擦系数调节仿真超出课标，课标仅要求理解惯性定律结论',
  },
  {
    key: 'newtonThirdLaw',
    name: '牛顿第三定律（作用力与反作用力）',
    description: '弹簧测力计对拉、小车碰撞、磁铁互吸三种方案验证F₁=-F₂',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 2,
    grade: '高一',
    tags: ['作用力', '反作用力', '等大反向', '弹簧测力计'],
    examLevel: '★★★',
  },
  {
    key: 'circularMotion',
    name: '圆周运动与向心力',
    description: '控制变量法探究向心力F=mv²/r，验证F∝v²、F∝1/r、F∝m',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 3,
    grade: '高一',
    tags: ['向心力', 'F=mv²/r', '角速度', '周期', '控制变量'],
    examLevel: '★★★',
    beyondCurriculum: true,
    beyondReason: '三模式控制变量法定量验证（F∝v²/F∝1/r/F∝m）超出课标，属于竞赛级实验深度',
  },
  {
    key: 'galileoFreeFall',
    name: '伽利略自由落体实验',
    description: '轻重物体同时落地验证、斜面冲淡重力实验、s-t²图像验证s∝t²',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 2,
    grade: '高一',
    tags: ['自由落体', 's=½gt²', '斜面实验', '伽利略', '推理法'],
    examLevel: '★★★',
    beyondCurriculum: true,
    beyondReason: '斜面冲淡重力历史实验还原+s-t²图像验证超出课标，课标仅要求了解自由落体规律',
  },
  {
    key: 'keplerLaws',
    name: '开普勒三大定律',
    description: '椭圆轨道、面积定律、T²∝a³，行星运动动画仿真',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 2,
    grade: '高一',
    tags: ['开普勒', '椭圆轨道', '面积定律', 'T²∝a³', '行星运动'],
    examLevel: '★★★',
    beyondCurriculum: true,
    beyondReason: '椭圆轨道+面积定律+T²∝a³定量仿真超出课标，课标仅要求定性了解行星运动规律',
  },
  {
    key: 'universalGravitation',
    name: '万有引力定律',
    description: 'F=GMm/r²，距离关系、质量关系、卡文迪什扭秤实验',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 2,
    grade: '高一',
    tags: ['万有引力', 'F=GMm/r²', '引力常数G', '卡文迪什', '平方反比'],
    examLevel: '★★★',
    beyondCurriculum: true,
    beyondReason: '卡文迪什扭秤仿真+三模式定量验证超出课标，课标仅要求掌握公式应用',
  },
  {
    key: 'cosmicVelocity',
    name: '三大宇宙速度与同步卫星',
    description: 'v₁=7.9km/s环绕、v₂=11.2km/s逃逸、v₃=16.7km/s飞出太阳系、同步卫星推导',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 3,
    grade: '高一',
    tags: ['宇宙速度', '环绕速度', '逃逸速度', '同步卫星', 'T=24h'],
    examLevel: '★★★',
    beyondCurriculum: true,
    beyondReason: 'v₂/v₃推导+同步卫星轨道仿真超出课标，课标仅要求知道第一宇宙速度',
  },
  {
    key: 'rocket',
    name: '运载火箭工作原理',
    description: '变质量系统推力模型、齐奥尔科夫斯基公式、多级火箭分离、发射动画仿真',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 3,
    grade: '高一',
    tags: ['火箭推力', '变质量', '齐奥尔科夫斯基', '多级分离', '动量守恒'],
    examLevel: '★',
    beyondCurriculum: true,
    beyondReason: '变质量系统+齐奥尔科夫斯基火箭方程+多级分离属于航天工程内容，超出中学物理课标',
  },
  {
    key: 'pendulum',
    name: '单摆测重力加速度',
    description: '用单摆周期公式 T=2π√(L/g) 测量当地重力加速度，探究摆长与周期的关系',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 2,
    grade: '高一',
    tags: ['单摆', '周期', '重力加速度', 'T=2π√(L/g)'],
    examLevel: '★★',
  },
  {
    key: 'simpleHarmonicMotion',
    name: '简谐振动',
    description: '弹簧振子位移-时间图像，探究振幅、周期、频率的关系，x=Acos(ωt+φ)',
    category: 'mechanics',
    subCategory: '高中力学',
    difficulty: 3,
    grade: '高一',
    tags: ['简谐振动', '弹簧振子', '正弦图像', '振幅', '周期', '相位'],
    examLevel: '★★★',
  },

  // ==================== 高中·电磁学（6个）====================
  {
    key: 'voltAmpereMethodHS',
    name: '伏安法测电阻（内接/外接）',
    description: '根据待测电阻阻值选择电流表内接法或外接法，分析系统误差来源（高中进阶版，初中基础伏安法见九年级）',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 3,
    grade: '高二',
    tags: ['内接法', '外接法', '系统误差'],
    examLevel: '★★★',
    preset: 'voltAmpereMethod',
  },
  {
    key: 'bulbIVCurve',
    name: '测绘小灯泡伏安特性曲线',
    description: '分压式接法，绘制I-V曲线，分析非线性原因（高中进阶版，初中测功率见九年级）',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 3,
    grade: '高二',
    tags: ['分压式', '伏安特性', '非线性', '温度影响'],
    examLevel: '★★★',
    preset: 'rheostatCurrentLimit',
  },
  {
    key: 'emfInternalResistance',
    name: '测量电源电动势和内阻',
    description: '两种电路方案，U-I图像截距与斜率，分析系统误差来源（重测量方法；规律探究见闭合电路欧姆定律）',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 3,
    grade: '高二',
    tags: ['电动势', '内阻', 'U-I图像', '系统误差'],
    examLevel: '★★★',
  },
  {
    key: 'multimeter',
    name: '练习使用多用电表',
    description: '欧姆调零、档位选择、二极管测量',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 2,
    grade: '高二',
    tags: ['多用电表', '欧姆档', '二极管'],
    examLevel: '★★',
  },
  {
    key: 'ampereForce',
    name: '探究安培力影响因素',
    description: '探究电流大小、导线长度、磁场强弱对安培力的影响',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 2,
    grade: '高二',
    tags: ['安培力', 'F=BIL', '左手定则'],
    examLevel: '★',
  },
  {
    key: 'lenzLaw',
    name: '楞次定律探究',
    description: '探究感应电流的方向：来拒去留',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 2,
    grade: '高二',
    tags: ['楞次定律', '感应电流', '磁通量变化'],
    examLevel: '★★',
  },

  // ==================== 高中·静电学（4个）====================
  {
    key: 'coulombLaw',
    name: '库仑定律探究',
    description: '探究电荷间作用力与电荷量、距离的关系，验证 F=kQ₁Q₂/r²',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 2,
    grade: '高二',
    tags: ['库仑定律', '点电荷', '控制变量', '扭秤'],
    examLevel: '★★★',
  },
  {
    key: 'electricFieldLine',
    name: '电场线与电场强度',
    description: '模拟点电荷、平行板电容器的电场线分布，探究E=F/q',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 2,
    grade: '高二',
    tags: ['电场线', '电场强度', '矢量叠加', '平行板'],
    examLevel: '★★★',
  },
  {
    key: 'electricPotential',
    name: '电势与电势差',
    description: '等势面可视化，电场力做功与电势差关系 W=qU',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 3,
    grade: '高二',
    tags: ['电势', '电势差', '等势面', 'W=qU'],
    examLevel: '★★★',
  },
  {
    key: 'capacitorCharge',
    name: '电容器充放电',
    description: '观察充电/放电电流变化，理解电容C=Q/U，RC时间常数',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 2,
    grade: '高二',
    tags: ['电容器', '充放电', 'C=Q/U', 'RC时间常数'],
    examLevel: '★★',
  },

  // ==================== 高中·电路分析（2个）====================
  {
    key: 'closedCircuitOhm',
    name: '闭合电路欧姆定律',
    description: '探究路端电压与电流关系 U=ε-Ir，内外电压分配（重规律探究；测量方法见电动势和内阻实验）',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 3,
    grade: '高二',
    tags: ['闭合电路', '电动势', '内阻', 'U-I图像'],
    examLevel: '★★★',
  },
  {
    key: 'meterConversion',
    name: '电表改装与校准',
    description: '电流表改装为电压表/大量程电流表，校准刻度',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 3,
    grade: '高二',
    tags: ['电表改装', '分流', '分压', '校准'],
    examLevel: '★★★',
  },

  // ==================== 高中·电磁感应（3个）====================
  {
    key: 'faradayLaw',
    name: '法拉第电磁感应定律',
    description: '探究感应电动势与磁通量变化率的关系 ε=NΔΦ/Δt',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 3,
    grade: '高二',
    tags: ['法拉第', '感应电动势', '磁通量', 'ε=NΔΦ/Δt'],
    examLevel: '★★★',
  },
  {
    key: 'selfInduction',
    name: '自感与互感',
    description: '观察自感现象（通电/断电自感），理解自感系数L',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 2,
    grade: '高二',
    tags: ['自感', '互感', '自感系数', '楞次定律'],
    examLevel: '★★',
  },
  {
    key: 'alternatingCurrent',
    name: '交流电的产生与描述',
    description: '线圈在磁场中转动产生交流电，理解峰值/有效值/频率',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 3,
    grade: '高二',
    tags: ['交流电', '正弦交流电', '有效值', '频率', '发电机'],
    examLevel: '★★★',
  },

  // ==================== 高中·电磁应用（2个）====================
  {
    key: 'lorentzForce',
    name: '洛伦兹力与带电粒子偏转',
    description: '带电粒子在磁场中做圆周运动，计算半径和周期',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 3,
    grade: '高三',
    tags: ['洛伦兹力', 'qvB', '圆周运动', '质谱仪', '回旋加速器'],
    examLevel: '★★★',
  },
  {
    key: 'electricFieldDeflection',
    name: '带电粒子在电场中的偏转',
    description: '带电粒子垂直进入匀强电场做类平抛运动，示波管原理，速度选择器',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 3,
    grade: '高三',
    tags: ['电场偏转', '类平抛', '示波管', '速度选择器'],
    examLevel: '★★★',
  },
  {
    key: 'transformer',
    name: '变压器与远距离输电',
    description: '探究变压器匝数比与电压比的关系，模拟远距离输电中的能量损耗',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 2,
    grade: '高二',
    tags: ['变压器', '匝数比', '远距离输电', '能量损耗', '互感'],
    examLevel: '★★',
  },
  {
    key: 'hallEffect',
    name: '霍尔效应',
    description: '载流导体在磁场中产生横向电势差，理解霍尔电压 UH=IB/nqd',
    category: 'electric',
    subCategory: '高中电磁学',
    difficulty: 3,
    grade: '高三',
    tags: ['霍尔效应', '霍尔电压', '载流子', '磁传感器'],
    examLevel: '★★',
  },


  // ==================== 高中·光学（3个）====================
  {
    key: 'glassRefraction',
    name: '测定玻璃折射率',
    description: '插针法确定光路，测量入射角和折射角',
    category: 'optics',
    subCategory: '高中光学',
    difficulty: 2,
    grade: '高二',
    tags: ['插针法', '折射率', 'n=sin i/sin r'],
    examLevel: '★★',
  },

  // ==================== 高中·光学（新增2个）====================
  {
    key: 'interferenceDiffraction',
    name: '光的干涉与衍射',
    description: '双缝干涉与单缝衍射实验，观察干涉条纹和衍射图样',
    category: 'optics',
    subCategory: '高中光学',
    difficulty: 3,
    grade: '高二',
    tags: ['双缝干涉', '单缝衍射', '明暗条纹', 'Δy=λL/d'],
    examLevel: '★★★',
    beyondCurriculum: true,
    beyondReason: '单缝衍射光强分布曲线+三种模式切换超出课标，课标仅要求定性观察干涉衍射现象',
  },
  {
    key: 'prismDispersion',
    name: '三棱镜色散',
    description: '白光通过三棱镜分散成七色光谱，探究色散规律',
    category: 'optics',
    subCategory: '高中光学',
    difficulty: 2,
    grade: '高二',
    tags: ['色散', '光谱', '折射率', 'n(λ)=n₀+B/λ²'],
    examLevel: '★★',
    beyondCurriculum: true,
    beyondReason: '柯西色散公式n(λ)=n₀+B/λ²+全内反射计算超出课标，课标仅要求定性了解色散现象',
  },
  {
    key: 'totalInternalReflection',
    name: '光的全反射',
    description: '演示全反射现象，探究临界角，模拟光纤导光原理',
    category: 'optics',
    subCategory: '高中光学',
    difficulty: 2,
    grade: '高二',
    tags: ['全反射', '临界角', '光纤', 'sinC=1/n'],
    examLevel: '★★',
  },
  {
    key: 'lightPolarization',
    name: '光的偏振',
    description: '用偏振片演示光的横波特性，旋转偏振片观察光强变化，理解马吕斯定律',
    category: 'optics',
    subCategory: '高中光学',
    difficulty: 2,
    grade: '高二',
    tags: ['偏振', '横波', '偏振片', '马吕斯定律'],
    examLevel: '★★',
  },

  // ==================== 近代物理 · 高二基础 ====================
  {
    key: 'photoelectric',
    name: '光电效应与普朗克常量测定',
    description: '模拟光电管实验，调节光频率、光强、反向电压，测绘I-U曲线，测定遏止电压，拟合普朗克常量',
    category: 'modern',
    subCategory: '高二基础',
    difficulty: 2,
    grade: '高二',
    tags: ['光电效应', '遏止电压', '普朗克常量', '截止频率'],
    examLevel: '★★',
  },
  {
    key: 'rutherford',
    name: '卢瑟福α粒子散射实验',
    description: '模拟α粒子轰击金箔，对比枣糕模型与原子核式模型，统计散射角度分布',
    category: 'modern',
    subCategory: '高二基础',
    difficulty: 2,
    grade: '高二',
    tags: ['α粒子散射', '原子核', '核式模型', '枣糕模型'],
    examLevel: '★★',
  },
  {
    key: 'bohr',
    name: '玻尔氢原子能级与光谱',
    description: '氢原子能级跃迁模拟，发射/吸收光子，生成氢原子线状光谱，计算光子波长',
    category: 'modern',
    subCategory: '高二基础',
    difficulty: 2,
    grade: '高二',
    tags: ['玻尔模型', '能级跃迁', '光谱线', '氢原子'],
    examLevel: '★★',
  },
  {
    key: 'radioactiveDecay',
    name: '放射性衰变与半衰期模拟',
    description: '虚拟原子核衰变统计，观察半衰期规律，α/β/γ射线穿透对比，辐射防护模拟',
    category: 'modern',
    subCategory: '高二基础',
    difficulty: 2,
    grade: '高二',
    tags: ['衰变', '半衰期', 'α射线', 'β射线', 'γ射线', '辐射防护'],
    examLevel: '★★',
  },
  // ==================== 近代物理 · 高二提高 ====================
  {
    key: 'blackbody',
    name: '黑体辐射光谱',
    description: '调节黑体温度观察辐射光谱变化，演示维恩位移定律，对比经典理论与普朗克量子解释',
    category: 'modern',
    subCategory: '高二提高',
    difficulty: 3,
    grade: '高二',
    tags: ['黑体辐射', '维恩位移', '普朗克', '量子化'],
    examLevel: '★★★',
  },
  {
    key: 'electronDoubleSlit',
    name: '电子双缝干涉 — 波粒二象性',
    description: '单电子逐点打屏累积干涉条纹，调节加速电压改变德布罗意波长，认识物质波',
    category: 'modern',
    subCategory: '高二提高',
    difficulty: 3,
    grade: '高二',
    tags: ['双缝干涉', '波粒二象性', '德布罗意波', '物质波'],
    examLevel: '★★★',
  },
  {
    key: 'nuclearReaction',
    name: '核裂变与核聚变模拟',
    description: '链式反应条件模拟，裂变聚变动画，演示质量亏损与质能方程',
    category: 'modern',
    subCategory: '高二提高',
    difficulty: 3,
    grade: '高二',
    tags: ['核裂变', '核聚变', '链式反应', '质能方程', '质量亏损'],
    examLevel: '★★★',
  },
  // ==================== 近代物理 · 高二挑战 ====================
  {
    key: 'relativity',
    name: '狭义相对论初步：时间膨胀与长度收缩',
    description: '高速运动参考系对比，调节运动速度实时观察洛伦兹因子、钟慢、尺缩效应',
    category: 'modern',
    subCategory: '高二挑战',
    difficulty: 3,
    grade: '高二',
    tags: ['狭义相对论', '时间膨胀', '长度收缩', '洛伦兹因子'],
    examLevel: '★★★',
  },
  {
    key: 'compton',
    name: '康普顿散射',
    description: '光子与自由电子碰撞，改变散射角观察光子波长偏移，验证光的粒子性',
    category: 'modern',
    subCategory: '高二挑战',
    difficulty: 3,
    grade: '高二',
    tags: ['康普顿散射', '光子', '散射角', '波长偏移'],
    examLevel: '★★★',
  },
  {
    key: 'millikan',
    name: '密立根油滴实验',
    description: '模拟油滴在电场中的受力平衡，测量元电荷e=1.6×10⁻¹⁹C，理解电荷量子化',
    category: 'modern',
    subCategory: '高二提高',
    difficulty: 3,
    grade: '高二',
    tags: ['密立根', '油滴', '元电荷', '电荷量子化', '受力平衡'],
    examLevel: '★★',
  },
]

/** 分类配置 */
export const CATEGORIES = [
  { key: 'mechanics', name: '力学', icon: '⚙️', color: '#FF9800' },
  { key: 'electric', name: '电学', icon: '⚡', color: '#4CAF50' },
  { key: 'thermal', name: '热学', icon: '🌡️', color: '#f44336' },
  { key: 'optics', name: '光学', icon: '🔬', color: '#2196F3' },
  { key: 'sound', name: '声学', icon: '🔊', color: '#9C27B0' },
  { key: 'modern', name: '近代物理', icon: '⚛️', color: '#607D8B' },
]

/** 难度标签 */
export const DIFFICULTY_LABELS = ['', '⭐ 基础', '⭐⭐ 提高', '⭐⭐⭐ 挑战']

/** 超纲实验列表 */
export const BEYOND_CURRICULUM = EXPERIMENT_CATALOG
  .filter(e => e.beyondCurriculum)
  .map(e => ({ key: e.key, name: e.name, reason: e.beyondReason }))

/** 考试等级说明 */
export const EXAM_LEVEL_DESC = {
  '★★★': '必考核心实验',
  '★★': '高频实验',
  '★': '了解类实验',
}
